Добавляет роутинг и стор
dormehOrg/fancyCoders pull request #1
Opened 2023-02-27 17:11 UTC by we1tkindzy

Добавляет роутинг, компонент private-route, константы (consts.ts) и папку sotre

2023-02-28 11:47 UTC, Dormeh reviewed
Валентин, я пару моментов подметил, что вызвало у меня вопросы. Посмотри пожалуйста

2023-02-28 11:47 UTC, Dormeh commented on packages/client/src/App.tsx
> +    <Routes>
у меня есть сомнение по поводу того что div отсутствует это лишает нас возможности стилизовать App
поправьте меня если я ошибаюсь
возможно понадобится сделать louder и в App вставить класс `loading` хотя можно это решить с помощью layout-а дополнительного для каждой страницы

2023-02-28 11:47 UTC, Dormeh commented on packages/client/src/consts.ts
> +  LOGIN: `/login`,
по поводу эндпоинтов тоже давайте подумаем оставить так либо поменять например на signin и signup

2023-02-28 13:15 UTC, we1tkindzy commented on packages/client/src/App.tsx
> +    <Routes>
Если добавлять div, то лучше тогда использовать styled-components?

2023-02-28 19:24 UTC, Dormeh commented on packages/client/src/App.tsx
> +    <Routes>
я думаю можно просто div добавить дефолтный, а в App.css уже добавим, если понадобится нужный стиль

2023-03-01 00:06 UTC, MariAnnaMari commented on packages/client/src/store/root-reducer.ts
> +import { combineReducers } from 'redux'
Этот файл я бы просто reducer назвала или rootReducer

2023-03-01 21:14 UTC, bin-umar requested changes
Привет! Первое, что бросается в глаза. Прощу убрать` .DS_Store` файлы в `.gitignore`. Также проще удалить package-lock.json, вы должны использовать yarn.

2023-03-02 08:12 UTC, bin-umar commented on packages/client/src/App.tsx
> +          // element={<ErrorPage />} Страница 404
Это типо на будущее? :)

2023-03-02 08:14 UTC, bin-umar approved these changes

2023-03-02 11:56 UTC, we1tkindzy commented on packages/client/src/App.tsx
> +          // element={<ErrorPage />} Страница 404
Да

2023-03-02 12:01 UTC, merged